name: Release

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/.ts/**'
      - '**/.nx/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nexus-api-key: ${{ secrets.NEXUS_API_KEY }}
      nexus-cookie-nxid-header: ${{ secrets.NEXUS_COOKIE_HEADER_NEXUSID }}
      nexus-cookie-sid-header: ${{ secrets.NEXUS_COOKIE_HEADER_SID_DEVELOP }}
      ts-api-key: ${{ secrets.TS_SERVICEACCOUNT }}

    with:
      sln-file-name: Digitalroot.Valheim.BetterWisps
      proj-file-name: Digitalroot.Valheim.BetterWisps
      #src-path: src
      #unit-test-path: UnitTests
      #skip-unit-tests: true
      #force-assembly-version: true
      #create-github-release: false
      #aws-region: us-west-2
      is-nuget-package: false
      #nuget-gh-upload: true
      #nuget-s3-upload: true
      #nuget-org-upload: true
      nexus-enable-upload: false
      nexus-mod-id: 2150
      ts-enable-upload: true
      ts-name: Better_Wisps
      ts-description: "Make the Wisp do a better job."
      ts-categories: "server-side client-side mistlands-update tweaks gear" #https://thunderstore.io/api/experimental/community/valheim/category/
      ts-dependencies: denikson-BepInExPack_Valheim@5.4.2105 ValheimModding-Jotunn@2.11.5      
